const beerData = [
  {
    _id: 1,
    image: '../images/beer_placeholder.jpg',
    title: 'Adnams Ghost Ship Bottle Beer 0.5%',
    brand: 'Adnams',
    abv: '0.5',
    calories: '23',
    type: 'Beer',
    ingredients: 'Water, Malted Barley, Malted Rye, Hops, Yeast',
    country: 'UK',
    volume: '500',
    description: 'This is a description I made up.',
    reviews: [
      { author: 'Alastair', body: 'I like this' },
      { author: 'Alastair', body: 'I like this' },
    ],
    rating: { overall: 4.2, taste: 4, realness: 4, value: 3 },
    upvote: 3,
  },
  {
    _id: 2,
    image: '../images/beer_placeholder.jpg',
    title: 'Adnams Ghost Ship Bottle Beer 0.5%',
    brand: 'Adnams',
    abv: '0.5',
    calories: '23',
    type: 'Beer',
    ingredients: 'Water, Malted Barley, Malted Rye, Hops, Yeast',
    country: 'UK',
    volume: '500',
    description: 'This is a description I made up.',
    reviews: [
      { author: 'Alastair', body: 'I like this' },
      { author: 'Alastair', body: 'I like this' },
    ],
    rating: { overall: 4.2, taste: 4, realness: 4, value: 3 },
    upvote: 6,
  },
  {
    _id: 3,
    image: '../images/beer_placeholder.jpg',
    title: 'Adnams Ghost Ship Bottle Beer 0.5%',
    brand: 'Adnams',
    abv: '0.5',
    calories: '23',
    type: 'Beer',
    ingredients: 'Water, Malted Barley, Malted Rye, Hops, Yeast',
    country: 'UK',
    volume: '500',
    description: 'This is a description I made up.',
    reviews: [
      { author: 'Alastair', body: 'I like this' },
      { author: 'Alastair', body: 'I like this' },
    ],
    rating: { overall: 4.2, taste: 4, realness: 4, value: 3 },
    upvote: 8,
  },
];

// export default beerData;
module.exports = beerData;
